[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[[redirects]]
from = "/*"
to = "/App.tsx"
status = 200

[dev]
  command = "python -m backend"
  port = 8888
  targetPort = 3000
  autoLaunch = true
  framework = "#custom"
